#ifdef BOARD_WEMOS32D1MINI
#define ESP32_CAN_TX_PIN GPIO_NUM_18
#define ESP32_CAN_RX_PIN GPIO_NUM_19
#define GWSERIAL_TX GPIO_NUM_17
#define GWSERIAL_RX GPIO_NUM_16
#define GWSERIAL_TYPE GWSERIAL_TYPE_BI
#endif